// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDppnvXljG-EG5Ux9KL2PY0UiSNbPOVLaY',
    appId: '1:236235732758:web:0537279b82158ec8258237',
    messagingSenderId: '236235732758',
    projectId: 'tercer-examen',
    authDomain: 'tercer-examen.firebaseapp.com',
    storageBucket: 'tercer-examen.appspot.com',
    measurementId: 'G-TKJ5W3DNNR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9sz8-XffIgzQ4ZF_TvMxBDWY_t96vAHI',
    appId: '1:236235732758:android:98dcace15904ce50258237',
    messagingSenderId: '236235732758',
    projectId: 'tercer-examen',
    storageBucket: 'tercer-examen.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaHYnR82et0Ww-DUdYQ6YTyn3vZLqpNMs',
    appId: '1:236235732758:ios:101ea1ac11df6c70258237',
    messagingSenderId: '236235732758',
    projectId: 'tercer-examen',
    storageBucket: 'tercer-examen.appspot.com',
    iosBundleId: 'com.example.tercerExamen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaHYnR82et0Ww-DUdYQ6YTyn3vZLqpNMs',
    appId: '1:236235732758:ios:101ea1ac11df6c70258237',
    messagingSenderId: '236235732758',
    projectId: 'tercer-examen',
    storageBucket: 'tercer-examen.appspot.com',
    iosBundleId: 'com.example.tercerExamen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDppnvXljG-EG5Ux9KL2PY0UiSNbPOVLaY',
    appId: '1:236235732758:web:90041d5dd2c7666b258237',
    messagingSenderId: '236235732758',
    projectId: 'tercer-examen',
    authDomain: 'tercer-examen.firebaseapp.com',
    storageBucket: 'tercer-examen.appspot.com',
    measurementId: 'G-CD3Y5WTHC4',
  );
}
